### PR TITLE
WIP Fix for latest version of Chrome

### PR DESCRIPTION
**Pull request by doublefint**
Upgrade to Polymer2
Upgrade dev tools and packages
Fix some errors

### CODE REVIEW

**Comment by DaniGuardiola** [comment]
This is great, I'm focusing on TimeDoser 3 now but if this fixes the TimeDoser 2 problems without changing the functionality and appearance, I'll merge it and release it.
I'll try to test it this weekend.
Just one question for now, I see that a bunch of files (the `modules/` ones) have been deleted, why is that?

Thanks.

**Comment by doublefint** [comment]
Hi, Dani!
As far as I understand src/timer/** is copy of  src/js/**
I use the Chrome version of the application, so I deleted everything that
is not used during the assembly with the grunt...
And in this new version, I found a few more errors, so this pull request
should be marked as WIP

**Comment by DaniGuardiola** [comment]
Cool!

**Comment by doublefint** [comment]
Hi, Dani!
As far as I understand, the errors I discovered relate to the existing code, and not to my changes. The current version more or less works.
It seems that you are using the Polymer in a very specific way ...

**Comment by DaniGuardiola** [comment]
Haha, yeah, this was the first project I used polymer with, so it's probably very messy. I don't remember how I made this. Thanks for your PR, I'll try to take a look at it soon, see if I can fix the current errors and publish the update.

**Comment by doublefint** [comment]
In any case, thank you very much for this application. It helps me a lot. Gracias!

**Comment by DaniGuardiola** [comment]
Hi @doublefint, I've made the decision to officially retire TimeDoser v2, so I'm closing this PR and archiving the repo. I hope sometime soon I can resume work on v3 (of which I actually have an exciting working prototype) so that it can completely replace v2.

Thank you for your interest, feel free to fork this repo if you wanna keep working on it. I'd also be glad to publish updates to the Chrome web store.

**Pull request closed without merging**
